# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{f2815e60-685f-415a-ab5d-bb77148bee59}',
        'interfaces': ['nsIAxioEngineAccessibility'],
        'contract_ids': ['@axiosozo.nl/engine-accessibility;1'],
        'type': 'axio::EngineAccessibility',
        'headers': ['mozilla/axio/AxioEngineAccessibility.h'],
        'constructor': 'axio::EngineAccessibility::GetSingleton',
        'singleton': True,
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
    },
]
